services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mixrank_mini
      POSTGRES_USER: mixrank
      POSTGRES_PASSWORD: mixrankpass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mixrank -d mixrank_mini"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  scanner:
    build:
      context: ../scanner
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://mixrank:mixrankpass@db:5432/mixrank_mini

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "runner.py"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://mixrank:mixrankpass@db:5432/mixrank_mini
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
